import React, { useState } from 'react';
import { QrCode, ShieldCheck, CheckCircle2, AlertTriangle, ArrowRight, Wallet } from 'lucide-react';
import { AppSettings, TenantWorkspace } from '../types';

interface MandatoryUpiModalProps {
  isOpen: boolean;
  currentTenant: TenantWorkspace | null;
  settings: AppSettings;
  onSaveUpiId: (upiId: string, merchantName?: string) => Promise<void>;
}

export const MandatoryUpiModal: React.FC<MandatoryUpiModalProps> = ({
  isOpen,
  currentTenant,
  settings,
  onSaveUpiId,
}) => {
  const initialName = currentTenant?.merchantName || settings?.merchantName || currentTenant?.companyName || settings?.appName || currentTenant?.ownerName || settings?.adminName || '';
  const [upiInput, setUpiInput] = useState(currentTenant?.upiId || settings?.upiId || '');
  const [merchantNameInput, setMerchantNameInput] = useState(initialName);
  const [isSaving, setIsSaving] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [verifiedSuccess, setVerifiedSuccess] = useState(false);

  if (!isOpen) return null;

  const validateUpiFormat = (upi: string): boolean => {
    const trimmed = upi.trim();
    if (!trimmed) return false;
    const upiRegex = /^[a-zA-Z0-9.\-_]{2,256}@[a-zA-Z0-9.\-_]{2,64}$/;
    return upiRegex.test(trimmed);
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    const cleanUpi = upiInput.trim();
    const cleanMerchantName = merchantNameInput.trim();

    if (!cleanUpi) {
      setErrorMsg('Please enter your UPI VPA ID (e.g. store@upi).');
      return;
    }

    if (!validateUpiFormat(cleanUpi)) {
      setErrorMsg('Invalid UPI ID format. Standard format is username@bank or mobile@upi (e.g., mystore@oksbi, 9876543210@paytm).');
      return;
    }

    if (!cleanMerchantName) {
      setErrorMsg('Please enter the Merchant / Payee Name associated with this UPI ID.');
      return;
    }

    setErrorMsg('');
    setIsSaving(true);

    try {
      await onSaveUpiId(cleanUpi, cleanMerchantName);
      setVerifiedSuccess(true);
    } catch (err: any) {
      setErrorMsg(err?.message || 'Failed to save UPI ID. Please try again.');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-fade-in">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl max-w-lg w-full p-6 sm:p-8 shadow-2xl relative overflow-hidden">
        {/* Top Accent Bar */}
        <div className="absolute top-0 inset-x-0 h-2 bg-gradient-to-r from-indigo-600 via-blue-600 to-emerald-500" />

        <div className="flex items-center gap-3.5 mb-5">
          <div className="w-12 h-12 rounded-2xl bg-indigo-50 dark:bg-indigo-950/80 text-indigo-600 dark:text-indigo-400 flex items-center justify-center shadow-inner flex-shrink-0">
            <QrCode className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-xl font-black text-slate-900 dark:text-white">
              Mandatory Payment UPI Setup
            </h3>
            <p className="text-xs font-semibold text-indigo-600 dark:text-indigo-400">
              Required for Direct Customer Settlements
            </p>
          </div>
        </div>

        {/* Clear Explanation Box */}
        <div className="p-4 bg-indigo-50/80 dark:bg-indigo-950/40 border border-indigo-100 dark:border-indigo-900/60 rounded-2xl mb-6 text-xs text-indigo-900 dark:text-indigo-200 leading-relaxed flex items-start gap-3">
          <Wallet className="w-5 h-5 text-indigo-600 dark:text-indigo-400 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-bold text-sm mb-1 text-indigo-950 dark:text-indigo-100">
              Why is this required?
            </p>
            <p>
              Your UPI ID is required so that payment QR Codes generated by the application will send customer payments directly to your own bank account.
            </p>
          </div>
        </div>

        {errorMsg && (
          <div className="p-3.5 bg-rose-50 dark:bg-rose-950/60 border border-rose-200 dark:border-rose-900 rounded-2xl mb-4 text-xs font-semibold text-rose-600 dark:text-rose-300 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 flex-shrink-0" />
            <span>{errorMsg}</span>
          </div>
        )}

        <form onSubmit={handleSave} className="space-y-4">
          <div>
            <label className="block text-xs font-black uppercase text-slate-500 dark:text-slate-400 tracking-wider mb-2">
              Merchant / Payee Name (As Registered with UPI) *
            </label>
            <input
              type="text"
              required
              value={merchantNameInput}
              onChange={(e) => {
                setMerchantNameInput(e.target.value);
                setErrorMsg('');
              }}
              placeholder="e.g. Sagar Traders, Ramesh Kumar"
              className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl text-base font-bold text-slate-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all"
            />
            <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-1">
              This exact name will be sent in UPI payment requests as Payee Name (pn).
            </p>
          </div>

          <div>
            <label className="block text-xs font-black uppercase text-slate-500 dark:text-slate-400 tracking-wider mb-2">
              Store / Business UPI ID (VPA) *
            </label>
            <div className="relative">
              <input
                type="text"
                required
                value={upiInput}
                onChange={(e) => {
                  setUpiInput(e.target.value);
                  setErrorMsg('');
                  setVerifiedSuccess(false);
                }}
                placeholder="e.g. mystore@oksbi, 9876543210@paytm"
                className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl font-mono text-base font-bold text-slate-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all"
              />
              {validateUpiFormat(upiInput) && (
                <div className="absolute right-3.5 top-1/2 -translate-y-1/2 flex items-center gap-1 text-xs font-bold text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/80 px-2.5 py-1 rounded-full border border-emerald-200 dark:border-emerald-800">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  Format Valid
                </div>
              )}
            </div>
            <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-1.5">
              Supports Google Pay, PhonePe, Paytm, BHIM, HDFC, SBI, ICICI & all Indian Bank VPAs.
            </p>
          </div>

          <div className="pt-2">
            <button
              type="submit"
              disabled={isSaving}
              className="w-full py-4 bg-gradient-to-r from-indigo-600 to-blue-600 hover:from-indigo-500 hover:to-blue-500 text-white font-black rounded-2xl shadow-xl shadow-indigo-500/25 transition-all cursor-pointer flex items-center justify-center gap-2 text-sm disabled:opacity-50"
            >
              {isSaving ? (
                <>
                  <span className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  <span>Verifying & Saving VPA...</span>
                </>
              ) : verifiedSuccess ? (
                <>
                  <ShieldCheck className="w-5 h-5 text-emerald-300" />
                  <span>Saved & Verified! Continuing...</span>
                </>
              ) : (
                <>
                  <span>Verify & Save UPI ID</span>
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
